# Generated by scripts/update-tap-formula.sh — do not edit by hand.
class Hyctl < Formula
  desc "Multi-model AI orchestration — one Cortex, many Heads"
  homepage "https://hydra.uvansa.com"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ankit373/hydra/releases/download/v1.0.1/hydra_1.0.1_darwin_arm64.tar.gz"
      sha256 "e3d98554490c8cb6356777757b03a0182e17237fd0caa9babee5b6d5eca36812"
    end
    on_intel do
      url "https://github.com/ankit373/hydra/releases/download/v1.0.1/hydra_1.0.1_darwin_amd64.tar.gz"
      sha256 "54b3cd4635310b65e425453a62eea03fe714ed95065d009adf5e0162d2a917da"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ankit373/hydra/releases/download/v1.0.1/hydra_1.0.1_linux_arm64.tar.gz"
      sha256 "4701bb57d882df2bdbe30aeabddf7b155140e98b65908c347078f2bbf637522e"
    end
    on_intel do
      url "https://github.com/ankit373/hydra/releases/download/v1.0.1/hydra_1.0.1_linux_amd64.tar.gz"
      sha256 "62a131c6a9689edbf9bad48a8493ffc53e9b56489b490e6174dc626f6a857380"
    end
  end

  def install
    bin.install "hyctl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyctl version")
  end
end
