# Generated by scripts/update-tap-formula.sh, do not edit by hand.
class Hyctl < Formula
  desc "Multi-model AI orchestration, one Cortex, many Heads"
  homepage "https://hydra.uvansa.com"
  version "1.4.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ankit373/hydra/releases/download/v1.4.1/hydra_1.4.1_darwin_arm64.tar.gz"
      sha256 "a9d8d889fc2d8bb6db1f8012cc9777337cc02cb4a35d92073ca739d7026a82a0"
    end
    on_intel do
      url "https://github.com/ankit373/hydra/releases/download/v1.4.1/hydra_1.4.1_darwin_amd64.tar.gz"
      sha256 "967b921cb7b51b2625db227d5911321d37c0700fda798aca0f066cc007557f0a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ankit373/hydra/releases/download/v1.4.1/hydra_1.4.1_linux_arm64.tar.gz"
      sha256 "8bab347d4616b423f5ff2a3dc6f5a57cbc5ae34c088a5caa724814706e615744"
    end
    on_intel do
      url "https://github.com/ankit373/hydra/releases/download/v1.4.1/hydra_1.4.1_linux_amd64.tar.gz"
      sha256 "76fac506e3806cf2ed9eab720eb2a6068e9aec6cc82ece894c2f2cdcf8c0c5be"
    end
  end

  def install
    bin.install "hyctl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyctl version")
  end
end
